### ISSUE TITLE
Auto-deploy dependabot config

### ISSUE THREAD

**Issue by Stebalien** [ipld/.github#28]
Dependabot is now configured through `.github/dependabot.yml`. We should deploy this in at least _some_ of our repos.

**Comment by marten-seemann** [comment]
Can you paste a sample config file here? Do we need this config file in all participating (Go) repos, or do we need a config option for that in `config.json`?

**Comment by Stebalien** [comment]
`.github/dependabot.yml`

```yaml
version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  labels:
    - "topic/dependencies"

```

And yeah... we need a config file in all participating go repos.
